### Site metadata

title: Официальный сайт Александра Лифшица
description: Starter template for a Jekyll 4 site - deployed with GH Actions and GH Pages
logo: "/assets/images/logo.png"

### Build settings

url: https://alexander-lifshitz.github.io
baseurl:

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - docs/
  - LICENSE
  - Makefile
  - sample.png
  - README.md

search_enabled: false
