### Site metadata

title: Александр Лифшиц
description: Официальный сайт Александра Лифшица

### Build settings

url: https://alexander-lifshitz.github.io
baseurl:

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - Makefile
  - sample.png
  - README.md

search_enabled: false
